### ISSUE TITLE
Typo, should be INVALID instead of INVALIDE

### ISSUE THREAD

**Issue by MattiaGuerra** [mukraj91/Linked-List#2]
https://github.com/mukraj91/Linked-List/blob/ccc2072da9d82cee7588c19dca762aebbeffc659/double-linked-list/DoubleLinkedListOperation.cpp#L52

**Comment by mukraj91** [comment]
Adapted as below.
enum DoubleLinkedListError {

      DOUBLE_LINKEDLIST_ERROR__INVALID = 0 ,
   }
